version: '3.8'

services:
  web-front:
    build: ./docker/node
    container_name: frontend-container
    ports:
      - 3000:3000
    volumes:
      - ./src/frontend:/app
    tty: true
  web-backend:
    build: ./docker/php
    container_name: backend-container
    ports:
      - 80:80
    volumes:
      - ./src/backend:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/apache/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
  db:
    image: mysql:8.2
    container_name: mysql-container
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sample-db
      MYSQL_USER: trainer
      MYSQL_PASSWORD: trainer
      TZ: 'Asia/Tokyo'
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
